services:
  prestalert.module:
    class: prestalert
    public: true
    factory: ["Module", "getInstanceByName"]
    arguments:
      - "prestalert"

  prestalert.context:
    class: Context
    public: true
    factory: ["Context", "getContext"]

  #####################
  # PS Account
  prestalert.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - "5.0"

  prestalert.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - "@prestalert.ps_accounts_installer"

  #####################
  # PS Billing
  prestalert.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
      - "@prestalert.ps_accounts_facade"
      - "@prestalert.context"
      - false # if true you are in sandbox mode, if false or empty not in sandbox

  prestalert.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - "@prestalert.ps_billings_context_wrapper"
      - "@prestalert.module"

  # Remove this if you don't need BillingService
  prestalert.ps_billings_service:
    class: PrestaShopCorp\Billing\Services\BillingService
    public: true
    arguments:
      - "@prestalert.ps_billings_context_wrapper"
      - "@prestalert.module"
