<?php $indexlist = array(
"access" => array("PRIMARY" => array("id_profile","id_tab"))
,"accessory" => array("accessory_product" => array("id_product_1","id_product_2"))
,"address" => array("PRIMARY" => array("id_address"),"address_customer" => array("id_customer"),"id_country" => array("id_country"),"id_state" => array("id_state"),"id_manufacturer" => array("id_manufacturer"),"id_supplier" => array("id_supplier"),"id_warehouse" => array("id_warehouse"))
,"address_format" => array("PRIMARY" => array("id_country"))
,"alias" => array("PRIMARY" => array("id_alias"),"alias" => array("alias"))
,"attachment" => array("PRIMARY" => array("id_attachment"))
,"attachment_lang" => array("PRIMARY" => array("id_attachment","id_lang"))
,"attribute" => array("PRIMARY" => array("id_attribute"),"attribute_group" => array("id_attribute_group"))
,"attribute_group" => array("PRIMARY" => array("id_attribute_group"))
,"attribute_group_lang" => array("PRIMARY" => array("id_attribute_group","id_lang"))
,"attribute_group_shop" => array("PRIMARY" => array("id_attribute_group","id_shop"),"id_shop" => array("id_shop"))
,"attribute_impact" => array("PRIMARY" => array("id_attribute_impact"),"id_product" => array("id_product","id_attribute"))
,"attribute_lang" => array("PRIMARY" => array("id_attribute","id_lang"),"id_lang" => array("id_lang","name"))
,"attribute_shop" => array("PRIMARY" => array("id_attribute","id_shop"),"id_shop" => array("id_shop"))
,"carrier" => array("PRIMARY" => array("id_carrier"),"deleted" => array("deleted","active"),"id_tax_rules_group" => array("id_tax_rules_group"))
,"carrier_group" => array("PRIMARY" => array("id_carrier","id_group"))
,"carrier_lang" => array("PRIMARY" => array("id_lang","id_shop","id_carrier"))
,"carrier_shop" => array("PRIMARY" => array("id_carrier","id_shop"),"id_shop" => array("id_shop"))
,"carrier_tax_rules_group_shop" => array("PRIMARY" => array("id_carrier","id_tax_rules_group","id_shop"))
,"carrier_zone" => array("PRIMARY" => array("id_carrier","id_zone"))
,"cart" => array("PRIMARY" => array("id_cart"),"cart_customer" => array("id_customer"),"id_address_delivery" => array("id_address_delivery"),"id_address_invoice" => array("id_address_invoice"),"id_carrier" => array("id_carrier"),"id_lang" => array("id_lang"),"id_currency" => array("id_currency"),"id_guest" => array("id_guest"),"id_shop_group" => array("id_shop_group"),"id_shop" => array("id_shop"))
,"cart_cart_rule" => array("PRIMARY" => array("id_cart","id_cart_rule"),"id_cart_rule" => array("id_cart_rule"))
,"cart_product" => array("cart_product_index" => array("id_cart","id_product"),"id_product_attribute" => array("id_product_attribute"))
,"cart_rule" => array("PRIMARY" => array("id_cart_rule"))
,"cart_rule_carrier" => array("PRIMARY" => array("id_cart_rule","id_carrier"))
,"cart_rule_combination" => array("PRIMARY" => array("id_cart_rule_1","id_cart_rule_2"),"id_cart_rule_1" => array("id_cart_rule_1"),"id_cart_rule_2" => array("id_cart_rule_2"))
,"cart_rule_country" => array("PRIMARY" => array("id_cart_rule","id_country"))
,"cart_rule_group" => array("PRIMARY" => array("id_cart_rule","id_group"))
,"cart_rule_lang" => array("PRIMARY" => array("id_cart_rule","id_lang"))
,"cart_rule_product_rule" => array("PRIMARY" => array("id_product_rule"))
,"cart_rule_product_rule_group" => array("PRIMARY" => array("id_product_rule_group"))
,"cart_rule_product_rule_value" => array("PRIMARY" => array("id_product_rule","id_item"))
,"cart_rule_shop" => array("PRIMARY" => array("id_cart_rule","id_shop"))
,"category" => array("PRIMARY" => array("id_category"),"category_parent" => array("id_parent"),"nleftright" => array("nleft","nright"),"nleftrightactive" => array("nleft","nright","active"),"level_depth" => array("level_depth"),"nright" => array("nright"),"nleft" => array("nleft"))
,"category_group" => array("PRIMARY" => array("id_category","id_group"),"id_category" => array("id_category"),"id_group" => array("id_group"))
,"category_lang" => array("PRIMARY" => array("id_category","id_shop","id_lang"),"category_name" => array("name"))
,"category_product" => array("PRIMARY" => array("id_category","id_product"),"id_product" => array("id_product"))
,"category_shop" => array("PRIMARY" => array("id_category","id_shop"))
,"cms" => array("PRIMARY" => array("id_cms"))
,"cms_block" => array("PRIMARY" => array("id_cms_block"))
,"cms_block_lang" => array("PRIMARY" => array("id_cms_block","id_lang"))
,"cms_block_page" => array("PRIMARY" => array("id_cms_block_page"))
,"cms_block_shop" => array("PRIMARY" => array("id_cms_block","id_shop"))
,"cms_category" => array("PRIMARY" => array("id_cms_category"),"category_parent" => array("id_parent"))
,"cms_category_lang" => array("PRIMARY" => array("id_cms_category","id_shop","id_lang"),"category_name" => array("name"))
,"cms_category_shop" => array("PRIMARY" => array("id_cms_category","id_shop"),"id_shop" => array("id_shop"))
,"cms_lang" => array("PRIMARY" => array("id_cms","id_shop","id_lang"))
,"cms_shop" => array("PRIMARY" => array("id_cms","id_shop"),"id_shop" => array("id_shop"))
,"compare" => array("PRIMARY" => array("id_compare"))
,"compare_product" => array("PRIMARY" => array("id_compare","id_product"))
,"configuration" => array("PRIMARY" => array("id_configuration"),"name" => array("name"),"id_shop" => array("id_shop"),"id_shop_group" => array("id_shop_group"))
,"configuration_kpi" => array("PRIMARY" => array("id_configuration_kpi"),"name" => array("name"),"id_shop" => array("id_shop"),"id_shop_group" => array("id_shop_group"))
,"configuration_kpi_lang" => array("PRIMARY" => array("id_configuration_kpi","id_lang"))
,"configuration_lang" => array("PRIMARY" => array("id_configuration","id_lang"))
,"connections" => array("PRIMARY" => array("id_connections"),"id_guest" => array("id_guest"),"date_add" => array("date_add"),"id_page" => array("id_page"))
,"connections_page" => array("PRIMARY" => array("id_connections","id_page","time_start"))
,"connections_source" => array("PRIMARY" => array("id_connections_source"),"connections" => array("id_connections"),"orderby" => array("date_add"),"http_referer" => array("http_referer"),"request_uri" => array("request_uri"))
,"contact" => array("PRIMARY" => array("id_contact"))
,"contact_lang" => array("PRIMARY" => array("id_contact","id_lang"))
,"contact_shop" => array("PRIMARY" => array("id_contact","id_shop"),"id_shop" => array("id_shop"))
,"country" => array("PRIMARY" => array("id_country"),"country_iso_code" => array("iso_code"),"country_" => array("id_zone"))
,"country_lang" => array("PRIMARY" => array("id_country","id_lang"))
,"country_shop" => array("PRIMARY" => array("id_country","id_shop"),"id_shop" => array("id_shop"))
,"currency" => array("PRIMARY" => array("id_currency"))
,"currency_shop" => array("PRIMARY" => array("id_currency","id_shop"),"id_shop" => array("id_shop"))
,"customer" => array("PRIMARY" => array("id_customer"),"customer_email" => array("email"),"customer_login" => array("email","passwd"),"id_customer_passwd" => array("id_customer","passwd"),"id_gender" => array("id_gender"),"id_shop_group" => array("id_shop_group"),"id_shop" => array("id_shop"))
,"customer_group" => array("PRIMARY" => array("id_customer","id_group"),"customer_login" => array("id_group"),"id_customer" => array("id_customer"))
,"customer_message" => array("PRIMARY" => array("id_customer_message"),"id_customer_thread" => array("id_customer_thread"),"id_employee" => array("id_employee"))
,"customer_message_sync_imap" => array("md5_header_index" => array("md5_header"))
,"customer_thread" => array("PRIMARY" => array("id_customer_thread"),"id_shop" => array("id_shop"),"id_lang" => array("id_lang"),"id_contact" => array("id_contact"),"id_customer" => array("id_customer"),"id_order" => array("id_order"),"id_product" => array("id_product"))
,"customization" => array("PRIMARY" => array("id_customization","id_cart","id_product","id_address_delivery"),"id_product_attribute" => array("id_product_attribute"))
,"customization_field" => array("PRIMARY" => array("id_customization_field"),"id_product" => array("id_product"))
,"customization_field_lang" => array("PRIMARY" => array("id_customization_field","id_lang","id_shop"))
,"customized_data" => array("PRIMARY" => array("id_customization","type","index"))
,"date_range" => array("PRIMARY" => array("id_date_range"))
,"delivery" => array("PRIMARY" => array("id_delivery"),"id_zone" => array("id_zone"),"id_carrier" => array("id_carrier","id_zone"),"id_range_price" => array("id_range_price"),"id_range_weight" => array("id_range_weight"))
,"employee" => array("PRIMARY" => array("id_employee"),"employee_login" => array("email","passwd"),"id_employee_passwd" => array("id_employee","passwd"),"id_profile" => array("id_profile"))
,"employee_shop" => array("PRIMARY" => array("id_employee","id_shop"),"id_shop" => array("id_shop"))
,"favorite_product" => array("PRIMARY" => array("id_favorite_product"))
,"feature" => array("PRIMARY" => array("id_feature"))
,"feature_lang" => array("PRIMARY" => array("id_feature","id_lang"),"id_lang" => array("id_lang","name"))
,"feature_product" => array("PRIMARY" => array("id_feature","id_product"),"id_feature_value" => array("id_feature_value"),"id_product" => array("id_product"))
,"feature_shop" => array("PRIMARY" => array("id_feature","id_shop"),"id_shop" => array("id_shop"))
,"feature_value" => array("PRIMARY" => array("id_feature_value"),"feature" => array("id_feature"))
,"feature_value_lang" => array("PRIMARY" => array("id_feature_value","id_lang"))
,"ganalytics" => array("PRIMARY" => array("id_google_analytics"),"id_order" => array("id_order"),"sent" => array("sent"))
,"gender" => array("PRIMARY" => array("id_gender"))
,"gender_lang" => array("PRIMARY" => array("id_gender","id_lang"),"id_gender" => array("id_gender"))
,"group" => array("PRIMARY" => array("id_group"))
,"group_lang" => array("PRIMARY" => array("id_group","id_lang"))
,"group_reduction" => array("PRIMARY" => array("id_group_reduction"),"id_group" => array("id_group","id_category"))
,"group_shop" => array("PRIMARY" => array("id_group","id_shop"),"id_shop" => array("id_shop"))
,"guest" => array("PRIMARY" => array("id_guest"),"id_customer" => array("id_customer"),"id_operating_system" => array("id_operating_system"),"id_web_browser" => array("id_web_browser"))
,"hook" => array("PRIMARY" => array("id_hook"),"hook_name" => array("name"))
,"hook_alias" => array("PRIMARY" => array("id_hook_alias"),"alias" => array("alias"))
,"hook_module" => array("PRIMARY" => array("id_module","id_hook","id_shop"),"id_hook" => array("id_hook"),"id_module" => array("id_module"),"position" => array("id_shop","position"))
,"hook_module_exceptions" => array("PRIMARY" => array("id_hook_module_exceptions"),"id_module" => array("id_module"),"id_hook" => array("id_hook"))
,"image" => array("PRIMARY" => array("id_image"),"idx_product_image" => array("id_image","id_product","cover"),"image_product" => array("id_product"),"id_product_cover" => array("id_product","cover"))
,"image_lang" => array("PRIMARY" => array("id_image","id_lang"),"id_image" => array("id_image"))
,"image_shop" => array("id_image" => array("id_image","id_shop","cover"),"id_shop" => array("id_shop"))
,"image_type" => array("PRIMARY" => array("id_image_type"),"image_type_name" => array("name"))
,"import_match" => array("PRIMARY" => array("id_import_match"))
,"info" => array("PRIMARY" => array("id_info"))
,"info_lang" => array("PRIMARY" => array("id_info","id_lang"))
,"lang" => array("PRIMARY" => array("id_lang"),"lang_iso_code" => array("iso_code"))
,"lang_shop" => array("PRIMARY" => array("id_lang","id_shop"),"id_shop" => array("id_shop"))
,"layered_category" => array("PRIMARY" => array("id_layered_category"),"id_category" => array("id_category","type"))
,"layered_filter" => array("PRIMARY" => array("id_layered_filter"))
,"layered_filter_shop" => array("PRIMARY" => array("id_layered_filter","id_shop"),"id_shop" => array("id_shop"))
,"layered_friendly_url" => array("PRIMARY" => array("id_layered_friendly_url"),"id_lang" => array("id_lang"),"url_key" => array("url_key"))
,"layered_indexable_attribute_group" => array("PRIMARY" => array("id_attribute_group"))
,"layered_indexable_attribute_group_lang_value" => array("PRIMARY" => array("id_attribute_group","id_lang"))
,"layered_indexable_attribute_lang_value" => array("PRIMARY" => array("id_attribute","id_lang"))
,"layered_indexable_feature" => array("PRIMARY" => array("id_feature"))
,"layered_indexable_feature_lang_value" => array("PRIMARY" => array("id_feature","id_lang"))
,"layered_indexable_feature_value_lang_value" => array("PRIMARY" => array("id_feature_value","id_lang"))
,"layered_price_index" => array("PRIMARY" => array("id_product","id_currency","id_shop"),"id_currency" => array("id_currency"),"price_min" => array("price_min"),"price_max" => array("price_max"))
,"layered_product_attribute" => array("PRIMARY" => array("id_attribute","id_product","id_shop"),"id_attribute_group" => array("id_attribute_group","id_attribute","id_product","id_shop"))
,"linksmenutop" => array("PRIMARY" => array("id_linksmenutop"),"id_shop" => array("id_shop"))
,"linksmenutop_lang" => array("id_linksmenutop" => array("id_linksmenutop","id_lang","id_shop"))
,"log" => array("PRIMARY" => array("id_log"))
,"mail" => array("PRIMARY" => array("id_mail"),"recipient" => array("recipient"))
,"manufacturer" => array("PRIMARY" => array("id_manufacturer"))
,"manufacturer_lang" => array("PRIMARY" => array("id_manufacturer","id_lang"))
,"manufacturer_shop" => array("PRIMARY" => array("id_manufacturer","id_shop"),"id_shop" => array("id_shop"))
,"memcached_servers" => array("PRIMARY" => array("id_memcached_server"))
,"message" => array("PRIMARY" => array("id_message"),"message_order" => array("id_order"),"id_cart" => array("id_cart"),"id_customer" => array("id_customer"),"id_employee" => array("id_employee"))
,"message_readed" => array("PRIMARY" => array("id_message","id_employee"))
,"meta" => array("PRIMARY" => array("id_meta"),"page" => array("page"))
,"meta_lang" => array("PRIMARY" => array("id_meta","id_shop","id_lang"),"id_shop" => array("id_shop"),"id_lang" => array("id_lang"))
,"module" => array("PRIMARY" => array("id_module"),"name" => array("name"))
,"module_access" => array("PRIMARY" => array("id_profile","id_module"))
,"module_country" => array("PRIMARY" => array("id_module","id_shop","id_country"))
,"module_currency" => array("PRIMARY" => array("id_module","id_shop","id_currency"),"id_module" => array("id_module"))
,"module_group" => array("PRIMARY" => array("id_module","id_shop","id_group"))
,"module_preference" => array("PRIMARY" => array("id_module_preference"),"employee_module" => array("id_employee","module"))
,"module_shop" => array("PRIMARY" => array("id_module","id_shop"),"id_shop" => array("id_shop"))
,"newsletter" => array("PRIMARY" => array("id"))
,"operating_system" => array("PRIMARY" => array("id_operating_system"))
,"order_carrier" => array("PRIMARY" => array("id_order_carrier"),"id_order" => array("id_order"),"id_carrier" => array("id_carrier"),"id_order_invoice" => array("id_order_invoice"))
,"order_cart_rule" => array("PRIMARY" => array("id_order_cart_rule"),"id_order" => array("id_order"),"id_cart_rule" => array("id_cart_rule"))
,"order_detail" => array("PRIMARY" => array("id_order_detail"),"order_detail_order" => array("id_order"),"product_id" => array("product_id"),"product_attribute_id" => array("product_attribute_id"),"id_tax_rules_group" => array("id_tax_rules_group"),"id_order_id_order_detail" => array("id_order","id_order_detail"))
,"order_detail_tax" => array("id_order_detail" => array("id_order_detail"),"id_tax" => array("id_tax"))
,"order_history" => array("PRIMARY" => array("id_order_history"),"order_history_order" => array("id_order"),"id_employee" => array("id_employee"),"id_order_state" => array("id_order_state"))
,"order_invoice" => array("PRIMARY" => array("id_order_invoice"),"id_order" => array("id_order"))
,"order_invoice_payment" => array("PRIMARY" => array("id_order_invoice","id_order_payment"),"order_payment" => array("id_order_payment"),"id_order" => array("id_order"))
,"order_invoice_tax" => array("id_tax" => array("id_tax"))
,"order_message" => array("PRIMARY" => array("id_order_message"))
,"order_message_lang" => array("PRIMARY" => array("id_order_message","id_lang"))
,"order_payment" => array("PRIMARY" => array("id_order_payment"),"order_reference" => array("order_reference"))
,"order_return" => array("PRIMARY" => array("id_order_return"),"order_return_customer" => array("id_customer"),"id_order" => array("id_order"))
,"order_return_detail" => array("PRIMARY" => array("id_order_return","id_order_detail","id_customization"))
,"order_return_state" => array("PRIMARY" => array("id_order_return_state"))
,"order_return_state_lang" => array("PRIMARY" => array("id_order_return_state","id_lang"))
,"order_slip" => array("PRIMARY" => array("id_order_slip"),"order_slip_customer" => array("id_customer"),"id_order" => array("id_order"))
,"order_slip_detail" => array("PRIMARY" => array("id_order_slip","id_order_detail"))
,"order_slip_detail_tax" => array("id_order_slip_detail" => array("id_order_slip_detail"),"id_tax" => array("id_tax"))
,"order_state" => array("PRIMARY" => array("id_order_state"),"module_name" => array("module_name"))
,"order_state_lang" => array("PRIMARY" => array("id_order_state","id_lang"))
,"orders" => array("PRIMARY" => array("id_order"),"reference" => array("reference"),"id_customer" => array("id_customer"),"id_cart" => array("id_cart"),"invoice_number" => array("invoice_number"),"id_carrier" => array("id_carrier"),"id_lang" => array("id_lang"),"id_currency" => array("id_currency"),"id_address_delivery" => array("id_address_delivery"),"id_address_invoice" => array("id_address_invoice"),"id_shop_group" => array("id_shop_group"),"current_state" => array("current_state"),"id_shop" => array("id_shop"),"date_add" => array("date_add"))
,"pack" => array("PRIMARY" => array("id_product_pack","id_product_item","id_product_attribute_item"))
,"page" => array("PRIMARY" => array("id_page"),"id_page_type" => array("id_page_type"),"id_object" => array("id_object"))
,"page_type" => array("PRIMARY" => array("id_page_type"),"name" => array("name"))
,"page_viewed" => array("PRIMARY" => array("id_page","id_date_range","id_shop"))
,"pagenotfound" => array("PRIMARY" => array("id_pagenotfound"),"date_add" => array("date_add"))
,"product" => array("PRIMARY" => array("id_product"),"product_supplier" => array("id_supplier"),"product_manufacturer" => array("id_manufacturer"),"id_category_default" => array("id_category_default"),"indexed" => array("indexed"),"date_add" => array("date_add"))
,"product_attachment" => array("PRIMARY" => array("id_product","id_attachment"))
,"product_attribute" => array("PRIMARY" => array("id_product_attribute"),"product_attribute_product" => array("id_product"),"reference" => array("reference"),"supplier_reference" => array("supplier_reference"),"product_default" => array("id_product","default_on"),"id_product_id_product_attribute" => array("id_product_attribute","id_product"))
,"product_attribute_combination" => array("PRIMARY" => array("id_attribute","id_product_attribute"),"id_product_attribute" => array("id_product_attribute"))
,"product_attribute_image" => array("PRIMARY" => array("id_product_attribute","id_image"),"id_image" => array("id_image"))
,"product_attribute_shop" => array("PRIMARY" => array("id_product_attribute","id_shop"))
,"product_carrier" => array("PRIMARY" => array("id_product","id_carrier_reference","id_shop"))
,"product_country_tax" => array("PRIMARY" => array("id_product","id_country"))
,"product_download" => array("PRIMARY" => array("id_product_download"),"product_active" => array("id_product","active"))
,"product_group_reduction_cache" => array("PRIMARY" => array("id_product","id_group"))
,"product_lang" => array("PRIMARY" => array("id_product","id_shop","id_lang"),"id_lang" => array("id_lang"),"name" => array("name"))
,"product_sale" => array("PRIMARY" => array("id_product"))
,"product_shop" => array("PRIMARY" => array("id_product","id_shop"),"id_category_default" => array("id_category_default"),"date_add" => array("date_add","active","visibility"))
,"product_supplier" => array("PRIMARY" => array("id_product_supplier"),"id_product" => array("id_product","id_product_attribute","id_supplier"))
,"product_tag" => array("PRIMARY" => array("id_product","id_tag"),"id_tag" => array("id_tag"))
,"profile" => array("PRIMARY" => array("id_profile"))
,"profile_lang" => array("PRIMARY" => array("id_profile","id_lang"))
,"quick_access" => array("PRIMARY" => array("id_quick_access"))
,"quick_access_lang" => array("PRIMARY" => array("id_quick_access","id_lang"))
,"range_price" => array("PRIMARY" => array("id_range_price"),"id_carrier" => array("id_carrier","delimiter1","delimiter2"))
,"range_weight" => array("PRIMARY" => array("id_range_weight"),"id_carrier" => array("id_carrier","delimiter1","delimiter2"))
,"referrer" => array("PRIMARY" => array("id_referrer"))
,"referrer_cache" => array("PRIMARY" => array("id_connections_source","id_referrer"))
,"referrer_shop" => array("PRIMARY" => array("id_referrer","id_shop"))
,"request_sql" => array("PRIMARY" => array("id_request_sql"))
,"required_field" => array("PRIMARY" => array("id_required_field"),"object_name" => array("object_name"))
,"risk" => array("PRIMARY" => array("id_risk"))
,"risk_lang" => array("PRIMARY" => array("id_risk","id_lang"),"id_risk" => array("id_risk"))
,"scene" => array("PRIMARY" => array("id_scene"))
,"scene_category" => array("PRIMARY" => array("id_scene","id_category"))
,"scene_lang" => array("PRIMARY" => array("id_scene","id_lang"))
,"scene_products" => array("PRIMARY" => array("id_scene","id_product","x_axis","y_axis"))
,"scene_shop" => array("PRIMARY" => array("id_scene","id_shop"),"id_shop" => array("id_shop"))
,"search_engine" => array("PRIMARY" => array("id_search_engine"))
,"search_index" => array("PRIMARY" => array("id_word","id_product"))
,"search_word" => array("PRIMARY" => array("id_word"),"id_lang" => array("id_lang","id_shop","word"))
,"sekeyword" => array("PRIMARY" => array("id_sekeyword"))
,"shop" => array("PRIMARY" => array("id_shop"),"id_shop_group" => array("id_shop_group"),"id_category" => array("id_category"),"id_theme" => array("id_theme"))
,"shop_group" => array("PRIMARY" => array("id_shop_group"))
,"shop_url" => array("PRIMARY" => array("id_shop_url"),"full_shop_url" => array("domain","physical_uri","virtual_uri"),"full_shop_url_ssl" => array("domain_ssl","physical_uri","virtual_uri"),"id_shop" => array("id_shop"))
,"smarty_cache" => array("PRIMARY" => array("id_smarty_cache"),"name" => array("name"),"cache_id" => array("cache_id"),"modified" => array("modified"))
,"specific_price" => array("PRIMARY" => array("id_specific_price"),"id_product" => array("id_product","id_shop","id_currency","id_country","id_group","id_customer","from_quantity","from","to"),"from_quantity" => array("from_quantity"),"id_specific_price_rule" => array("id_specific_price_rule"),"id_cart" => array("id_cart"))
,"specific_price_priority" => array("PRIMARY" => array("id_specific_price_priority","id_product"),"id_product" => array("id_product"))
,"specific_price_rule" => array("PRIMARY" => array("id_specific_price_rule"),"id_product" => array("id_shop","id_currency","id_country","id_group","from_quantity","from","to"))
,"specific_price_rule_condition" => array("PRIMARY" => array("id_specific_price_rule_condition"),"id_specific_price_rule_condition_group" => array("id_specific_price_rule_condition_group"))
,"specific_price_rule_condition_group" => array("PRIMARY" => array("id_specific_price_rule_condition_group","id_specific_price_rule"))
,"state" => array("PRIMARY" => array("id_state"),"id_country" => array("id_country"),"name" => array("name"),"id_zone" => array("id_zone"))
,"statssearch" => array("PRIMARY" => array("id_statssearch"))
,"stock" => array("PRIMARY" => array("id_stock"),"id_warehouse" => array("id_warehouse"),"id_product" => array("id_product"),"id_product_attribute" => array("id_product_attribute"))
,"stock_available" => array("PRIMARY" => array("id_stock_available"),"product_sqlstock" => array("id_product","id_product_attribute","id_shop","id_shop_group"),"id_shop" => array("id_shop"),"id_shop_group" => array("id_shop_group"),"id_product" => array("id_product"),"id_product_attribute" => array("id_product_attribute"))
,"stock_mvt" => array("PRIMARY" => array("id_stock_mvt"),"id_stock" => array("id_stock"),"id_stock_mvt_reason" => array("id_stock_mvt_reason"))
,"stock_mvt_reason" => array("PRIMARY" => array("id_stock_mvt_reason"))
,"stock_mvt_reason_lang" => array("PRIMARY" => array("id_stock_mvt_reason","id_lang"))
,"store" => array("PRIMARY" => array("id_store"))
,"store_shop" => array("PRIMARY" => array("id_store","id_shop"),"id_shop" => array("id_shop"))
,"supplier" => array("PRIMARY" => array("id_supplier"))
,"supplier_lang" => array("PRIMARY" => array("id_supplier","id_lang"))
,"supplier_shop" => array("PRIMARY" => array("id_supplier","id_shop"),"id_shop" => array("id_shop"))
,"supply_order" => array("PRIMARY" => array("id_supply_order"),"id_supplier" => array("id_supplier"),"id_warehouse" => array("id_warehouse"),"reference" => array("reference"))
,"supply_order_detail" => array("PRIMARY" => array("id_supply_order_detail"),"id_supply_order" => array("id_supply_order"),"id_product" => array("id_product"),"id_product_attribute" => array("id_product_attribute"),"id_product_product_attribute" => array("id_product","id_product_attribute"))
,"supply_order_history" => array("PRIMARY" => array("id_supply_order_history"),"id_supply_order" => array("id_supply_order"),"id_employee" => array("id_employee"),"id_state" => array("id_state"))
,"supply_order_receipt_history" => array("PRIMARY" => array("id_supply_order_receipt_history"),"id_supply_order_detail" => array("id_supply_order_detail"),"id_supply_order_state" => array("id_supply_order_state"))
,"supply_order_state" => array("PRIMARY" => array("id_supply_order_state"))
,"supply_order_state_lang" => array("PRIMARY" => array("id_supply_order_state","id_lang"))
,"tab" => array("PRIMARY" => array("id_tab"),"class_name" => array("class_name"),"id_parent" => array("id_parent"))
,"tab_lang" => array("PRIMARY" => array("id_tab","id_lang"))
,"tab_module_preference" => array("PRIMARY" => array("id_tab_module_preference"),"employee_module" => array("id_employee","id_tab","module"))
,"tag" => array("PRIMARY" => array("id_tag"),"tag_name" => array("name"),"id_lang" => array("id_lang"))
,"tax" => array("PRIMARY" => array("id_tax"))
,"tax_lang" => array("PRIMARY" => array("id_tax","id_lang"))
,"tax_rule" => array("PRIMARY" => array("id_tax_rule"),"id_tax_rules_group" => array("id_tax_rules_group"),"id_tax" => array("id_tax"),"category_getproducts" => array("id_tax_rules_group","id_country","id_state","zipcode_from"))
,"tax_rules_group" => array("PRIMARY" => array("id_tax_rules_group"))
,"tax_rules_group_shop" => array("PRIMARY" => array("id_tax_rules_group","id_shop"),"id_shop" => array("id_shop"))
,"theme" => array("PRIMARY" => array("id_theme"))
,"theme_meta" => array("PRIMARY" => array("id_theme_meta"),"id_theme_2" => array("id_theme","id_meta"),"id_theme" => array("id_theme"),"id_meta" => array("id_meta"))
,"theme_specific" => array("PRIMARY" => array("id_theme","id_shop","entity","id_object"))
,"themeconfigurator" => array("PRIMARY" => array("id_item"))
,"timezone" => array("PRIMARY" => array("id_timezone"))
,"warehouse" => array("PRIMARY" => array("id_warehouse"))
,"warehouse_carrier" => array("PRIMARY" => array("id_warehouse","id_carrier"),"id_warehouse" => array("id_warehouse"),"id_carrier" => array("id_carrier"))
,"warehouse_product_location" => array("PRIMARY" => array("id_warehouse_product_location"),"id_product" => array("id_product","id_product_attribute","id_warehouse"))
,"warehouse_shop" => array("PRIMARY" => array("id_warehouse","id_shop"),"id_warehouse" => array("id_warehouse"),"id_shop" => array("id_shop"))
,"web_browser" => array("PRIMARY" => array("id_web_browser"))
,"webservice_account" => array("PRIMARY" => array("id_webservice_account"),"key" => array("key"))
,"webservice_account_shop" => array("PRIMARY" => array("id_webservice_account","id_shop"),"id_shop" => array("id_shop"))
,"webservice_permission" => array("PRIMARY" => array("id_webservice_permission"),"resource_2" => array("resource","method","id_webservice_account"),"resource" => array("resource"),"method" => array("method"),"id_webservice_account" => array("id_webservice_account"))
,"wishlist" => array("PRIMARY" => array("id_wishlist"))
,"wishlist_email" => array()
,"wishlist_product" => array("PRIMARY" => array("id_wishlist_product"))
,"wishlist_product_cart" => array()
,"zone" => array("PRIMARY" => array("id_zone"))
,"zone_shop" => array("PRIMARY" => array("id_zone","id_shop"),"id_shop" => array("id_shop"))
);